# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promote', '0001_initial'),
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='promote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_collection', to='promote.Promote'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reation_type',
            field=models.CharField(choices=[('normal', 'normal'), ('smile', 'smile'), ('love', 'love'), ('wish', 'wish'), ('like', 'like'), ('dislike', 'dislike')], default='Like', max_length=200),
        ),
    ]
