# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-09 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_auto_20171009_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reation_type',
            new_name='reaction_type',
        ),
    ]
