# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-09 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('shop', '0041_auto_20171005_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('endTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cover', models.IntegerField(default=0, null=True)),
                ('maxCover', models.IntegerField(default=0, null=True)),
                ('isActive', models.NullBooleanField(choices=[(True, 'Yes I acknowledge this'), (False, 'No, I do not like this')], default=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='promote_collections', to='collection.Collection')),
                ('products', models.ManyToManyField(blank=True, related_name='promote_products', to='shop.Product')),
            ],
        ),
    ]
