# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promote', '0002_auto_20171015_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promote',
            old_name='collections',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='promote',
            old_name='products',
            new_name='product',
        ),
    ]
