# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-18 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='isActive',
            field=models.NullBooleanField(choices=[(True, 'Yes I acknowledge this'), (False, 'No, I do not like this')], default=False),
        ),
    ]
