# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_discount_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_collection', to='collection.Collection'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_product', to='shop.Product'),
        ),
    ]
