# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-09 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20170828_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
