# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('shop', '0037_auto_20170717_1531'),
        ('authentication', '0002_auto_20170717_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishedCollections',
            field=models.ManyToManyField(blank=True, related_name='wished_collections', to='collection.Collection'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishedProducts',
            field=models.ManyToManyField(blank=True, related_name='wished_products', to='shop.Product'),
        ),
    ]
