# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-05 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170828_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='store',
        ),
    ]
