# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-05 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_activity_store'),
        ('shop', '0041_auto_20171005_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_table', to='shop.Table'),
        ),
    ]
