# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storeId',
            field=models.PositiveIntegerField(blank=True, default=111, null=True),
        ),
    ]
