# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_storeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storeId',
        ),
        migrations.AddField(
            model_name='product',
            name='storeName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
