# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170623_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
