# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_store_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
