# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170623_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
