# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170626_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
