# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170626_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
