# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170626_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
