# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_store_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storeName',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Store'),
        ),
    ]
