# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20170628_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('V\xe9tement et accessoires', 'V\xe9tement et accessoires'), ('Bijoux', 'Bijoux'), ('Founiture cr\xe9atives', 'Founiture cr\xe9atives'), ('Mariages', 'Mariages'), ('Maison', 'Maison'), ('Enfant et b\xe9b\xe9', 'Enfant et b\xe9b\xe9')], max_length=200, null=True),
        ),
    ]
