# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
