# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20170629_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to=shop.models.renameP),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(null=True, upload_to=shop.models.renameP),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(null=True, upload_to=shop.models.renameP),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(null=True, upload_to=shop.models.renameP),
        ),
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.ImageField(null=True, upload_to=shop.models.rename),
        ),
    ]
