# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='facebookPage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='locationUrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phoneNumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
