# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20170710_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Ptype',
            field=models.IntegerField(choices=[(1, 'Faits main'), (2, 'Vintage')], default=2, null=True),
        ),
    ]
