# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20170710_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('Vetement et accessoires', 'Vetement et accessoires'), ('Bijoux', 'Bijoux'), ('Founiture creatives', 'Founiture creatives'), ('Mariages', 'Mariages'), ('Maison', 'Maison'), ('Enfant et bebe', 'Enfant et bebe')], max_length=200, null=True),
        ),
    ]
