# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-17 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0036_auto_20170710_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='smiles',
            field=models.ManyToManyField(blank=True, related_name='smiles_of_this_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='wishes',
            field=models.ManyToManyField(blank=True, related_name='wishes_of_this_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_of_this_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
