# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-22 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20170717_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='albumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=shop.models.rename)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Store')),
            ],
        ),
    ]
