# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_store_visiters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='visiters',
            new_name='visitors',
        ),
    ]
