# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-05 02:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_activity_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0040_auto_20170823_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('facebookPage', models.CharField(max_length=200, null=True)),
                ('locationUrl', models.TextField(null=True)),
                ('isActive', models.NullBooleanField(choices=[(None, 'I do not know now'), (True, 'Yes I acknowledge this'), (False, 'No, I do not like this')], default=None)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitors', models.ManyToManyField(blank=True, related_name='tables_visiters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='StoreImage',
            new_name='TableImage',
        ),
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.RemoveField(
            model_name='store',
            name='visitors',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.RemoveField(
            model_name='tableimage',
            name='store',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='albumimage',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Table'),
        ),
        migrations.AddField(
            model_name='product',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Table'),
        ),
        migrations.AddField(
            model_name='tableimage',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Table'),
        ),
    ]
