# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-12 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20171005_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='smiles',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wishes',
        ),
    ]
