# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-12 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20171012_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cCategorie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
