# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='relatedProducts',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
