# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20170717_1531'),
        ('messenger', '0003_message_relatedproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='relatedProducts',
        ),
        migrations.AddField(
            model_name='message',
            name='relatedProducts',
            field=models.ManyToManyField(blank=True, related_name='relatedProducts', to='shop.Product'),
        ),
    ]
