# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-24 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20170721_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to=messenger.models.rename),
        ),
    ]
