# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-24 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='product',
        ),
    ]
